function [ind, sub] = MatrixEdgeIndex(dim, thk)
% Matrix Edge Index

sub = [reshape(repmat(1:dim(1) - thk(2), thk(1), 1), 1, []), ...
    repmat(dim(1) - thk(2) + 1:dim(1), 1, dim(2) - thk(3)), ...
    reshape(repmat(dim(1):-1:1 + thk(4), thk(3), 1), 1, []), ...
    repmat(1:thk(4), 1, dim(2) - thk(1)); ...
    repmat(1:thk(1), 1, dim(1) - thk(2)), ...
    reshape(repmat(1:dim(2) - thk(3), thk(2), 1), 1, []), ...
    repmat(dim(2) - thk(3) + 1:dim(2), 1, dim(1) - thk(4)), ...
    reshape(repmat(dim(2):-1:1 + thk(1), thk(4), 1), 1, [])];

ind = sub2ind(dim, sub(1, :), sub(2, :));

end

